### ISSUE TITLE
【提案】例外文字列のキャッチ

### ISSUE THREAD

**Issue by kokubojw** [syamashi/cppmodule#1]
https://github.com/syamashi/cppmodule/blob/master/cpp01/ex05/Human.cpp

例外文字列は
https://en.cppreference.com/w/cpp/error/exception/what
でキャッチ可能。

**Comment by syamashi** [comment]
エラー処理はスルーで！cpp05くらいから指示があるので、それまではなかったことに。

cpp05から
catch(std::exception &e)
なる便利なエラーキャッチしてます。

cpp05まで、catch(std:bad_alloc)してるかもしれません…。
