### ISSUE TITLE
cpp08/ex02  Makefile

### ISSUE THREAD

**Issue by sasakiyudai** [syamashi/cppmodule#3]
# 概要　cpp08/ex02  -Wall -Werror -Wextra 指定が抜けている
# 目的　レビュー失格を防ぐ・ステッカーを貰う
# 提案内容　
## before
cpp08/ex02/Makefile
```
CFLAGS = 
```
## after
cpp08/ex02/Makefile
```
CFLAGS =  -Wall -Werror -Wextra

**Comment by syamashi** [comment]
++syudai
https://github.com/syamashi/cppmodule/commit/ef20c4f4bf915fcf0dec9fb592aa4bf3c520fea3
