### ISSUE TITLE
言われそうなやつ

### ISSUE THREAD

**Issue by mkokubo42** [syamashi/cppmodule#5]
https://github.com/syamashi/cppmodule/blob/master/cpp01/ex07/main.cpp
- 置換後文字列と置換先文字列のチェック抜けてる（str2）？
Make a program called replace that takes a filename and two strings, let’s call them
s1 and s2, that are NOT empty.

**Comment by syamashi** [comment]
NOT empty.
 たしかにーー…。

「何かを空文字に置換する」は全然あるかと思って、第二引数の空文字はOKにしてます。仕様。
empty = 入力なし、と解釈。
けど課題的には、"" もエラー対象にしたほうがいいかもしれない。
